name: CUDA workflows
description: |
  This workflow demonstrates how to use the NVIDIA CUDA Toolkit
on:
  workflow_dispatch:

jobs:
  cuda11:
    runs-on: 4-core-gpu
    steps:
      - uses: actions/checkout@v4.1.1
      - name: Install CUDA Toolkit 12.4
        uses: ./.github/actions/install-cuda
      - name: show CUDA version
        run: nvcc --version
      - name: show GPU
        run: nvidia-smi