name: CUDA workflows

on:
  workflow_dispatch:

jobs:
  cuda12:
    runs-on: 4-core-ubuntu-gpu-t4
    steps:
      - uses: actions/checkout@v4.1.1
      - name: Install CUDA Toolkit 12.4
        uses: ./.github/actions/setup-cuda
      - name: show CUDA version
        run: nvcc --version
      - name: show GPU
        run: |
          which nvidia-smi
          nvidia-smi
      - name: show /usr/local
        run: ls -l /usr/local
      - name: show $CUDA/bin
        run: ls -l $CUDA/bin
      - name: show env
        run: env
  cuda114gpu:
    runs-on: 4-core-ubuntu-gpu-t4
    steps:
      - uses: actions/checkout@v4
      - name: umask
        run: sudo umask
      - name: Look around
        run: |
          ls -ld /var
          ls -ld /var/log
      - name: Install CUDA Toolkit 11.4.4
        uses: robandpdx-org/cuda-toolkit@fix-log-upload-error
        id: cuda-toolkit
        with:
          cuda: '11.4.4'
      - name: Look around
        run: |
          ls -ld /var
          ls -ld /var/log
          ls -l /var/log
      - name: show /usr/local
        run: ls -l /usr/local
      - name: show $CUDA_PATH/bin
        run: ls -l $CUDA_PATH/bin
      - name: show env
        run: env
      - name: show CUDA version
        run: $CUDA_PATH/bin/nvcc --version
      - name: show GPU
        run: |
          which nvidia-smi
          nvidia-smi
